using System;
using System.Collections.Generic;

namespace BlueBrick.Audit.Contracts
{
    /// <summary>
    /// Audit run request. Per BB-M001 packet section 10, carries the
    /// target, mode, options (e.g. bounded all-config limit), and
    /// correlation ID. Operation ID is generated by
    /// <see cref="BlueBrick.Audit.Core.AuditReceiptFactory"/> at receipt
    /// construction time, not supplied by the caller.
    /// </summary>
    [Serializable]
    public sealed class AuditRunRequest
    {
        /// <summary>Caller-assigned correlation ID (use the same value across audit/preview/receipt chains).</summary>
        public string CorrelationId { get; set; }

        /// <summary>Operation mode. Slice 1/2 only ever sets <see cref="AuditOperationMode.MOCK"/> or <see cref="AuditOperationMode.READ_ONLY_ANALYST"/>.</summary>
        public AuditOperationMode Mode { get; set; }

        /// <summary>Target descriptor (hashed identity, doc type, active config, expected state version, expected dirty).</summary>
        public AuditTarget Target { get; set; }

        /// <summary>Hard cap on number of configurations read in bounded all-config mode; 0 or null = active-only.</summary>
        public int? ConfigurationReadLimit { get; set; }

        /// <summary>If true, attempt to read all configurations up to <see cref="ConfigurationReadLimit"/>; otherwise active configuration only.</summary>
        public bool ReadAllConfigurations { get; set; }

        /// <summary>List of explicitly requested property names. The adapter must read at least the BB-M001 initial governed property set per packet section 17 even if this list is empty.</summary>
        public List<string> RequestedPropertyNames { get; set; } = new List<string>();
    }
}
